---
- name: 'update and upgrade packages.' # sudo apt upgrade
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: remove unneeded deps # sudo apt autoremove
  become: yes
  apt:
    autoremove: yes
- name: install deps # sudo apt install nodejs npm
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes
- name: install pm2 # sudo npm install pm2 -g
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes