# ---
# - name: 'update and upgrade packages.'
#   become: yes
#   apt:
#     upgrade: yes
#     update_cache: yes
#     cache_valid_time: 86400
# - name: remove unneeded deps
#   become: yes
#   apt:
#     autoremove: yes
# - name: install deps
#   become: yes
#   apt:
#     name: ['nodejs', 'npm']
#     state: latest
#     update_cache: yes
# - name: install pm2
#   become: yes
#   npm:
#     name: pm2
#     global: yes
#     state: latest
#     production: yes

# # - name: "move files to server"
# #   become: yes
# #   synchronize:
# #   src: /root/project/backend/dist
# #   dest: ./udapeople-circle
# #   recursive: true




# - name: extract artifact
#   become: yes
#   unarchive:
#     src: artifact.tar.gz
#     dest: .





# - name: start app
#   become: yes
#   shell: |
#     pm2 delete all
#     pm2 start npm -- start


- name:  create backend directory
  file:
    path: "$HOME/backend"
    state: directory
     
- name: "unarchive backend directory"
  unarchive:
    src: artifact.tar.gz
    dest: "$HOME/backend"


- name: "install node dependencies"
  shell: |
    cd ~/backend
    npm install

- name: "start backend"
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: "check if backend is running"
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "config pm2 to start as a service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save
