version: 2.1
            
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend # go to frontend directory
            npm install # install dependencies
            npm run build # build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
             cd backend # go to backend directory
             npm install # install dependencies
             npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-frontend:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout # check out
        - restore_cache: 
            keys: [frontend-build]
        - run: 
            name: Run frontend utest
            command: |
              cd frontend # go to frontend directory
              npm install # install dependencies
              npm run test # test-frontend       

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
    - checkout # check out
    - restore_cache: 
        keys: [backend-build]
    - run: 
          name: Run frontend utest
          command: |
            cd backend # go to backend directory
            npm install # install dependencies
            npm run test # test-backend   
            npm audit fix



workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      